### ISSUE TITLE
[extend-poly-lines] problem of accuracy

### ISSUE THREAD

**Issue by ZasoGD** [TheSned/IITCPlugins#11]
A few months ago I also started to write a similar plugin.
After much investigation I used [Leaflet.Geodesic](https://github.com/henrythasler/Leaflet.Geodesic/) (I tried also other codes, without success).
But my development was blocked when I realized that something was not accurated:
if i link `p1` to `p2` and `p2` to `p3` seems ok, but isn't so. because if I link `A` to `C`, `AC` not cross `B`. 

For the moment I have not been able to solve the problem or to reduce the error. I hope you'll have better luck than me.

> I edited your plugin to test the `AC` line (green dashed).
In this example `AB` distance is about 30km ![image](https://cloud.githubusercontent.com/assets/4642351/19154704/efc17ac0-8bdb-11e6-828d-e92de30482f3.png)

**Comment by TheSned** [comment]
I don't understand. I don't see labels p1, p2, p3, or A, B, C on your drawing. Can you show an example with intel links where the line is inaccurate?

**Comment by TheSned** [comment]
Actually I think I found an example.

First link these 2 portals:
https://www.ingress.com/intel?ll=76.538332,-68.747946&z=17&pll=76.538332,-68.747946
to 
https://www.ingress.com/intel?ll=64.839277,11.144516&z=17&pll=64.839277,11.144516

Then look at these 2 portals:
https://www.ingress.com/intel?ll=55.69296,-120.560508&z=17&pll=55.69296,-120.560508
and
https://www.ingress.com/intel?ll=63.393,13.09938&z=17&pll=63.393,13.09938

According to the red dashed lines, both these 2 portals should be North of the existing link and therefore should not cross the existing link. But when you draw the line between them, link 2 crosses link 1.

I think this might be due to the projection used by Leaflet.Geodesic being slightly off from the one the intel map uses.

The error is very small though. I don't expect it to impact most people using this plugin for its intended purpose. I will look into it though.

**Comment by TheSned** [comment]
I figured out that the error is due to using an ellipsoid vs spherical projection. IITC use L.CRS.EPSG3857 (which from what I can tell is a misnomer because it uses the L.Projection.SphericalMercator projection rather than the WGS84 ellipsoid). Since the vincenty formulae use the WGS84 ellipsoid, that is where the error comes in. I have found in tests that if I change the following in the vincenty functions: `var ellipsoid = { a: 6367000, b: 6367000, f: 0 }; // Sphere` it works. However I think there may be a more simple formula for spherical calculations which I want to use.
